import "server-only";

import type { Agent, Asset, Client, ClientCompetitor, ClientContextDoc, ClientReport, Job } from "@/lib/types";
import { effectiveDominantColors } from "@/lib/branding";

/* ── Shared helpers ──────────────────────────────────────────────────── */

function roughAge(ts: number): string {
  const secs = Math.floor((Date.now() - ts) / 1000);
  if (secs < 60) return "just now";
  const mins = Math.floor(secs / 60);
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days < 30) return `${days}d ago`;
  return new Date(ts).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

const DONE_STATUSES = new Set<Asset["status"]>(["approved", "delivered", "published"]);

const DOC_TYPE_LABELS: Record<string, string> = {
  "brand-voice": "Brand Voice",
  "market-strategy": "Market Strategy",
  "competitor-analysis": "Competitor Analysis",
  "product-information": "Product Information",
  "branding-guidelines": "Branding Guidelines",
  "client-guidelines": "Client Guidelines",
  "action-plan": "Action Plan",
};

export function buildCopilotSystemPrompt(
  client: Client,
  report: ClientReport | null,
  competitors: ClientCompetitor[],
  agents: Agent[],
  jobs: Job[],
  assets: Asset[],
  contextDocs: ClientContextDoc[] = [],
): string {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const parts: string[] = [
    `You are the AI Copilot for **${client.name}** — an intelligent account manager embedded in the Karos CMO platform.`,
    `You have complete visibility into this client's brand profile, competitor landscape, content history, and strategy documents.`,
    `Be concise, strategic, and specific. Never hallucinate data — only reference what is listed below. Today is ${today}.`,
    "",
  ];

  // Client profile
  parts.push("## CLIENT PROFILE");
  parts.push(`- **Name:** ${client.name}`);
  if (client.website) parts.push(`- **Website:** ${client.website}`);
  if (client.industry) parts.push(`- **Industry:** ${client.industry}`);
  if (client.description) parts.push(`- **Description:** ${client.description}`);
  if (client.contactEmail) parts.push(`- **Contact:** ${client.contactEmail}`);
  parts.push(`- **Status:** ${client.status}`);
  parts.push("");

  // Context documents (new pipeline — primary source of truth)
  // Staff/internal docs take priority; client-tier docs as fallback
  const priorityDocs = contextDocs.filter(
    (d) => d.tier === "internal" || d.tier === "client",
  );
  if (priorityDocs.length > 0) {
    parts.push(
      "## CLIENT CONTEXT DOCUMENTS",
      "Generated by the multi-agent research pipeline. These are the primary source of brand and strategy intelligence.",
      "",
    );
    // Deduplicate: prefer internal tier when both exist for same docType
    const seen = new Set<string>();
    for (const doc of priorityDocs) {
      if (seen.has(doc.docType)) continue;
      seen.add(doc.docType);
      const label = DOC_TYPE_LABELS[doc.docType] ?? doc.docType;
      const tierLabel = doc.tier === "internal" ? "Internal" : "Client-facing";
      parts.push(`### ${label} [${tierLabel} · v${doc.version}]`);
      // Include up to 800 chars of content per doc (strip frontmatter)
      const stripped = doc.content.replace(/^---[\s\S]*?---\n?/, "").trim();
      const excerpt = stripped.slice(0, 800);
      parts.push(excerpt + (stripped.length > 800 ? "\n[…truncated]" : ""));
      parts.push("");
    }
  }

  // Legacy intel report (metadata only — scores/grades are deprecated from display)
  if (report) {
    parts.push("## REPORT METADATA");
    if (report.reportDate) parts.push(`- **Report Date:** ${report.reportDate}`);
    if (report.businessType) parts.push(`- **Business Type:** ${report.businessType}`);
    if (report.techStack) parts.push(`- **Tech Stack:** ${report.techStack}`);
    if (report.founded) parts.push(`- **Founded:** ${report.founded}`);

    if (report.swot) {
      const { strengths, weaknesses, opportunities, threats } = report.swot;
      parts.push("", "### SWOT");
      if (strengths?.length) parts.push(`- **Strengths:** ${strengths.join(" | ")}`);
      if (weaknesses?.length) parts.push(`- **Weaknesses:** ${weaknesses.join(" | ")}`);
      if (opportunities?.length) parts.push(`- **Opportunities:** ${opportunities.join(" | ")}`);
      if (threats?.length) parts.push(`- **Threats:** ${threats.join(" | ")}`);
    }

    if (report.recommendations.length > 0) {
      parts.push("", "### Strategic Recommendations");
      for (const r of report.recommendations.slice(0, 6)) {
        const tag = r.tag ? ` [${r.tag}]` : "";
        const desc = r.description ? ` — ${r.description}` : "";
        parts.push(`${r.number}. **${r.title}**${desc}${tag}`);
      }
    }
    parts.push("");
  }

  // Competitors
  if (competitors.length > 0) {
    parts.push("## COMPETITOR TRACKER");
    for (const c of competitors) {
      const meta: string[] = [c.company];
      if (c.marketTier) meta.push(c.marketTier);
      if (c.threatLevel) meta.push(`${c.threatLevel} threat`);
      if (c.overlap) meta.push(`overlap: ${c.overlap}`);
      if (c.url) meta.push(c.url);
      parts.push(`- ${meta.join(" · ")}`);
      if (c.keyStrengths?.length) parts.push(`  Strengths: ${c.keyStrengths.join(", ")}`);
      if (c.keyWeaknesses?.length) parts.push(`  Weaknesses: ${c.keyWeaknesses.join(", ")}`);
      if (c.positioning) parts.push(`  Positioning: ${c.positioning}`);
    }
    parts.push("");
  }

  // Branding — always use effectiveDominantColors() to support both legacy scalar fields
  // and the new dominantColors[] array. Never read g.primaryAccent etc. directly here.
  const g = client.brandingGuidelines;
  if (g) {
    parts.push("## BRANDING GUIDELINES (Agent-Active)");
    const colors = effectiveDominantColors(g);
    colors.forEach((c) => {
      const label = c.role ? `Color ${c.dominanceRank} (${c.role})` : `Color ${c.dominanceRank}`;
      parts.push(`- **${label}:** ${c.hex}`);
    });
    if (g.fontHeading) parts.push(`- **Heading Font:** ${g.fontHeading}`);
    if (g.fontBody) parts.push(`- **Body Font:** ${g.fontBody}`);
    if (g.toneKeywords?.length) parts.push(`- **Tone Keywords:** ${g.toneKeywords.join(", ")}`);
    if (g.guidelines) parts.push(`- **Written Guidelines:** ${g.guidelines}`);
    parts.push("");
  }

  // Active agents
  const activeAgents = agents.filter((a) => a.isActive && !a.isSystem);
  if (activeAgents.length > 0) {
    parts.push("## ACTIVE AI AGENTS");
    for (const a of activeAgents) {
      const caps = a.capabilities?.length ? ` [${a.capabilities.join(", ")}]` : "";
      parts.push(`- **${a.name}**: ${a.description ?? ""}${caps}`);
    }
    parts.push("");
  }

  // Recent jobs
  if (jobs.length > 0) {
    parts.push("## RECENT JOB HISTORY");
    for (const j of jobs.slice(0, 10)) {
      parts.push(`- ${j.agentName}: "${j.title}" — **${j.status}**`);
    }
    parts.push("");
  }

  // Asset summary
  if (assets.length > 0) {
    const byType = assets.reduce<Record<string, number>>((acc, a) => {
      acc[a.type] = (acc[a.type] ?? 0) + 1;
      return acc;
    }, {});
    parts.push("## GENERATED ASSETS");
    for (const [type, count] of Object.entries(byType)) {
      parts.push(`- ${type}: ${count} asset${count !== 1 ? "s" : ""}`);
    }
    parts.push("");
  }

  parts.push(
    "## TOOLS",
    "You have two tools:",
    "- **update_branding_guidelines** — updates brand colors, fonts, or tone keywords. Confirm the specific change with the user before calling.",
    "- **send_support_email** — escalates issues to the Karos Labs team. Use when the user reports a problem.",
  );

  return parts.join("\n");
}

/* ── Agent-specific copilot prompt ──────────────────────────────────── */

/**
 * Builds the system prompt for agent-mode chat: adopts the agent's persona,
 * injects numbered draft assets (referenced by ID for edit_draft targeting),
 * lists published outputs, recent runs, and describes all 4 available tools.
 */
export function buildAgentCopilotSystemPrompt(
  agent: Agent,
  client: Client,
  agentJobs: Job[],
  agentAssets: Asset[],
  contextDocs: ClientContextDoc[] = [],
): string {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const draftAssets = agentAssets.filter((a) => a.status === "draft");
  const doneAssets = agentAssets.filter((a) => DONE_STATUSES.has(a.status));

  const parts: string[] = [
    `You are the AI Copilot for the **${agent.name}** agent — managing the content pipeline for **${client.name}**.`,
    `Today is ${today}. Be concise, specific, and action-oriented. Never hallucinate content not listed below.`,
    "",
    "## AGENT PERSONA",
    agent.systemPrompt,
    "",
    "## YOUR COPILOT CAPABILITIES",
    "- Discuss, review, and improve existing drafts",
    "- Trigger new content generation runs on request (/run, 'create new', 'generate', etc.)",
    "- Edit a specific draft's content or status inline — confirm with the user before applying",
    "- Answer questions about this agent's performance and output history",
    "",
  ];

  // Input fields — model needs these to collect inputs before calling run_agent
  if (agent.fields?.length > 0) {
    parts.push("## INPUT FIELDS (collect before triggering a run)");
    for (const f of agent.fields) {
      const req = f.required ? " [required]" : " [optional]";
      const def = f.defaultValue ? ` · default: "${f.defaultValue}"` : "";
      const hint = f.placeholder ? ` · hint: ${f.placeholder}` : "";
      parts.push(`- **${f.label}** (key: \`${f.key}\`)${req}${def}${hint}`);
    }
    parts.push("");
  }

  // Client context snapshot
  parts.push(`## CLIENT: ${client.name}`);
  if (client.website) parts.push(`Website: ${client.website}`);
  if (client.industry) parts.push(`Industry: ${client.industry}`);
  if (client.description) parts.push(`About: ${client.description}`);
  const g = client.brandingGuidelines;
  if (g) {
    const bits: string[] = [];
    const colors = effectiveDominantColors(g);
    if (colors.length) bits.push(`Colors: ${colors.map((c) => c.hex).join(", ")}`);
    if (g.toneKeywords?.length) bits.push(`Tone: ${g.toneKeywords.join(", ")}`);
    if (bits.length) parts.push(`Brand: ${bits.join(" · ")}`);
  }
  parts.push("");

  // Brand + product context docs (most relevant to content agents)
  const relevantDocs = contextDocs
    .filter((d) => ["brand-voice", "product-information", "branding-guidelines"].includes(d.docType))
    .slice(0, 2);
  for (const doc of relevantDocs) {
    const label = DOC_TYPE_LABELS[doc.docType] ?? doc.docType;
    const stripped = doc.content.replace(/^---[\s\S]*?---\n?/, "").trim();
    parts.push(`### ${label}`);
    parts.push(stripped.slice(0, 500) + (stripped.length > 500 ? "\n[…truncated]" : ""));
    parts.push("");
  }

  // Draft assets — numbered so the user can say "fix draft #2"
  parts.push(`## ACTIVE DRAFTS — ${draftAssets.length} AWAITING REVIEW`);
  if (draftAssets.length === 0) {
    parts.push("No drafts currently pending.");
  } else {
    for (let i = 0; i < draftAssets.length; i++) {
      const a = draftAssets[i];
      const excerpt = a.content.slice(0, 300);
      parts.push(
        `\n**Draft #${i + 1}** — asset ID: \`${a.id}\``,
        `Title: ${a.title}`,
        `Content: ${excerpt}${a.content.length > 300 ? "…" : ""}`,
        `Created: ${roughAge(a.createdAt)}`,
      );
    }
  }
  parts.push("");

  // Published / done assets (read-only history)
  if (doneAssets.length > 0) {
    parts.push(`## PUBLISHED OUTPUTS (${doneAssets.length} total)`);
    for (const a of doneAssets.slice(0, 5)) {
      parts.push(`- [${a.status}] ${a.title} — ${roughAge(a.createdAt)}`);
    }
    parts.push("");
  }

  // Recent runs
  if (agentJobs.length > 0) {
    parts.push(`## RECENT RUNS (${agentJobs.length} total)`);
    for (const j of agentJobs.slice(0, 5)) {
      parts.push(`- ${j.title} — **${j.status}** (${roughAge(j.createdAt)})`);
    }
    parts.push("");
  }

  parts.push(
    "## TOOLS",
    "- **run_agent** — start a new generation run. Collect required field values from the user first; apply defaults for optional fields. Confirm before launching.",
    "- **edit_draft** — update a draft's content or status. Reference drafts by their asset ID above. Always confirm the exact change with the user before calling.",
    "- **update_branding_guidelines** — update brand colors, fonts, or tone keywords. Confirm before calling.",
    "- **send_support_email** — escalate issues to the Karos Labs team.",
  );

  return parts.join("\n");
}
