import "server-only";

import type { Asset, Client, ClientCompetitor, ClientContextDoc, ClientReport, Job } from "@/lib/types";
import { effectiveDominantColors } from "@/lib/branding";

/* ── Shared helpers ──────────────────────────────────────────────────── */

const DOC_TYPE_LABELS: Record<string, string> = {
  "brand-voice": "Brand Voice",
  "market-strategy": "Market Strategy",
  "competitor-analysis": "Competitor Analysis",
  "product-information": "Product Information",
  "branding-guidelines": "Branding Guidelines",
  "target-audience": "Target Audience",
  "client-guidelines": "Client Guidelines",
  "action-plan": "Action Plan",
};

export function buildCopilotSystemPrompt(
  client: Client,
  report: ClientReport | null,
  competitors: ClientCompetitor[],
  jobs: Job[],
  assets: Asset[],
  contextDocs: ClientContextDoc[] = [],
): string {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const parts: string[] = [
    `You are the AI Copilot for **${client.name}** — an intelligent account manager embedded in the Karos CMO platform.`,
    `You have complete visibility into this client's brand profile, competitor landscape, content history, and strategy documents.`,
    `Be concise, strategic, and specific. Never hallucinate data — only reference what is listed below. Today is ${today}.`,
    "",
    // The panel renders replies through the portal's document renderer, which
    // supports exactly the marks listed here. Anything outside that set reached
    // the client as literal characters — hash marks, table pipes, stray
    // asterisks (QA F89) — and this prompt being written in Markdown is what
    // taught the model to answer in it.
    "## HOW TO WRITE YOUR REPLIES",
    "Your replies are rendered in a narrow chat panel that supports only: **bold**, *italics*, `code`, hyphen bullets, numbered lists, and > blockquotes.",
    "- Do NOT use ## or ### headings. For a multi-section answer, open each section with a short **bold label** on its own line.",
    "- Do NOT use tables — a table is unreadable at this width. Use bullets instead.",
    "- Sentence case, no title case. Keep paragraphs to two or three sentences.",
    "- Never show the client raw field names, database ids, or internal status codes.",
    "",
  ];

  // Client profile
  parts.push("## CLIENT PROFILE");
  parts.push(`- **Name:** ${client.name}`);
  if (client.website) parts.push(`- **Website:** ${client.website}`);
  if (client.industry) parts.push(`- **Industry:** ${client.industry}`);
  if (client.description) parts.push(`- **Description:** ${client.description}`);
  if (client.contactEmail) parts.push(`- **Contact:** ${client.contactEmail}`);
  parts.push(`- **Status:** ${client.status}`);
  parts.push("");

  // Context documents (new pipeline — primary source of truth)
  // Staff/internal docs take priority; client-tier docs as fallback
  const priorityDocs = contextDocs.filter(
    (d) => d.tier === "internal" || d.tier === "client",
  );
  if (priorityDocs.length > 0) {
    parts.push(
      "## CLIENT CONTEXT DOCUMENTS",
      "Generated by the multi-agent research pipeline. These are the primary source of brand and strategy intelligence.",
      "",
    );
    // Deduplicate: prefer internal tier when both exist for same docType
    const seen = new Set<string>();
    for (const doc of priorityDocs) {
      if (seen.has(doc.docType)) continue;
      seen.add(doc.docType);
      const label = DOC_TYPE_LABELS[doc.docType] ?? doc.docType;
      const tierLabel = doc.tier === "internal" ? "Internal" : "Client-facing";
      parts.push(`### ${label} [${tierLabel} · v${doc.version}]`);
      // Include up to 800 chars of content per doc (strip frontmatter)
      const stripped = doc.content.replace(/^---[\s\S]*?---\n?/, "").trim();
      const excerpt = stripped.slice(0, 800);
      parts.push(excerpt + (stripped.length > 800 ? "\n[…truncated]" : ""));
      parts.push("");
    }
  }

  // Legacy intel report (metadata only — scores/grades are deprecated from display)
  if (report) {
    parts.push("## REPORT METADATA");
    if (report.reportDate) parts.push(`- **Report Date:** ${report.reportDate}`);
    if (report.businessType) parts.push(`- **Business Type:** ${report.businessType}`);
    if (report.techStack) parts.push(`- **Tech Stack:** ${report.techStack}`);
    if (report.founded) parts.push(`- **Founded:** ${report.founded}`);

    if (report.swot) {
      const { strengths, weaknesses, opportunities, threats } = report.swot;
      parts.push("", "### SWOT");
      if (strengths?.length) parts.push(`- **Strengths:** ${strengths.join(" | ")}`);
      if (weaknesses?.length) parts.push(`- **Weaknesses:** ${weaknesses.join(" | ")}`);
      if (opportunities?.length) parts.push(`- **Opportunities:** ${opportunities.join(" | ")}`);
      if (threats?.length) parts.push(`- **Threats:** ${threats.join(" | ")}`);
    }

    if (report.recommendations.length > 0) {
      parts.push("", "### Strategic Recommendations");
      for (const r of report.recommendations.slice(0, 6)) {
        const tag = r.tag ? ` [${r.tag}]` : "";
        const desc = r.description ? ` — ${r.description}` : "";
        parts.push(`${r.number}. **${r.title}**${desc}${tag}`);
      }
    }
    parts.push("");
  }

  // Competitors
  if (competitors.length > 0) {
    parts.push("## COMPETITOR TRACKER");
    for (const c of competitors) {
      const meta: string[] = [c.company];
      if (c.marketTier) meta.push(c.marketTier);
      if (c.threatLevel) meta.push(`${c.threatLevel} threat`);
      if (c.overlap) meta.push(`overlap: ${c.overlap}`);
      if (c.url) meta.push(c.url);
      parts.push(`- ${meta.join(" · ")}`);
      if (c.keyStrengths?.length) parts.push(`  Strengths: ${c.keyStrengths.join(", ")}`);
      if (c.keyWeaknesses?.length) parts.push(`  Weaknesses: ${c.keyWeaknesses.join(", ")}`);
      if (c.positioning) parts.push(`  Positioning: ${c.positioning}`);
    }
    parts.push("");
  }

  // Branding — always use effectiveDominantColors() to support both legacy scalar fields
  // and the new dominantColors[] array. Never read g.primaryAccent etc. directly here.
  const g = client.brandingGuidelines;
  if (g) {
    parts.push("## BRANDING GUIDELINES (Agent-Active)");
    const colors = effectiveDominantColors(g);
    colors.forEach((c) => {
      const label = c.role ? `Color ${c.dominanceRank} (${c.role})` : `Color ${c.dominanceRank}`;
      parts.push(`- **${label}:** ${c.hex}`);
    });
    if (g.fontHeading) parts.push(`- **Heading Font:** ${g.fontHeading}`);
    if (g.fontBody) parts.push(`- **Body Font:** ${g.fontBody}`);
    if (g.toneKeywords?.length) parts.push(`- **Tone Keywords:** ${g.toneKeywords.join(", ")}`);
    if (g.guidelines) parts.push(`- **Written Guidelines:** ${g.guidelines}`);
    parts.push("");
  }

  // Recent jobs
  if (jobs.length > 0) {
    parts.push("## RECENT JOB HISTORY");
    for (const j of jobs.slice(0, 10)) {
      parts.push(`- ${j.agentName}: "${j.title}" — **${j.status}**`);
    }
    parts.push("");
  }

  // Asset summary
  if (assets.length > 0) {
    const byType = assets.reduce<Record<string, number>>((acc, a) => {
      acc[a.type] = (acc[a.type] ?? 0) + 1;
      return acc;
    }, {});
    parts.push("## GENERATED ASSETS");
    for (const [type, count] of Object.entries(byType)) {
      parts.push(`- ${type}: ${count} asset${count !== 1 ? "s" : ""}`);
    }
    parts.push("");
  }

  parts.push(
    "## TOOLS",
    "You have two tools:",
    "- **update_branding_guidelines** — updates brand colors, fonts, or tone keywords. Confirm the specific change with the user before calling.",
    "- **send_support_email** — escalates issues to the Karos Labs team. Use when the user reports a problem.",
  );

  return parts.join("\n");
}
