/**
 * `## Change Log` preservation across a document regeneration.
 *
 * Two rules are in tension here:
 *
 *  1. The generator must NEVER invent a change log. A model-written history of
 *     edits it did not witness is fabricated provenance, which is why the
 *     generation prompt forbids the section (pipeline.ts, CRITICAL OUTPUT RULES)
 *     and why the template's trailing meta sections are excluded from the
 *     truncation probe.
 *  2. A change log that a HUMAN or an IMPORT maintained is the provenance trail
 *     for the document — the lab-imported action plans carry one — and a
 *     regeneration replaces every stored row, so without a carry-forward that
 *     trail is destroyed on the next run.
 *
 * Both hold at once by making the order structural: strip whatever the generator
 * produced, then re-attach the section read off the PREVIOUSLY STORED document
 * of the same docType + tier. A fabricated log always dies; only a log that was
 * already on the stored document survives, and it can never be duplicated
 * because the strip runs first. Repeated regenerations therefore converge on
 * exactly one section that grows only by the dated lines added here.
 *
 * Pure and client-safe — no Firestore, no model calls, no `server-only`, so the
 * behaviour is unit-testable without standing up the pipeline.
 */

/** The `## Change Log` heading itself. Deliberately not `###` — a subsection of
 *  that name inside a body is content, not the trailing meta section. */
const HEADING_RE = /^##[ \t]+Change[ \t]*Log[ \t]*$/im;

/** The next top-level section, which ends the change log. */
const NEXT_SECTION_RE = /^##[ \t]/m;

/** A change-log entry: a markdown list item. `- 2026-07-24 — imported — …` */
const ENTRY_RE = /^([-*])[ \t]+\S/;

/** The line appended to mark a regeneration, minus its list marker. */
const REGEN_NOTE = "Document regenerated by the intel pipeline; earlier entries preserved.";

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Half-open [start, end) bounds of the first change-log section, or null. */
function locate(content: string): { start: number; end: number } | null {
  const m = HEADING_RE.exec(content);
  if (!m) return null;
  const start = m.index;
  // `$` stops before the newline, so the remainder always opens with it — a
  // `^##` match at index 0 of the remainder is impossible.
  const afterHeading = start + m[0].length;
  const next = NEXT_SECTION_RE.exec(content.slice(afterHeading));
  return { start, end: next ? afterHeading + next.index : content.length };
}

/**
 * The `## Change Log` section of a document — heading through end-of-section
 * (the next `## ` heading, or EOF). Returns null when the document has none.
 */
export function extractChangeLog(content: string): string | null {
  const at = locate(content ?? "");
  if (!at) return null;
  return content.slice(at.start, at.end).trimEnd();
}

/**
 * Remove every `## Change Log` section. Loops rather than replacing once: a
 * generator that echoed the section twice must not leave one behind for the
 * carry-forward to sit next to.
 */
export function stripChangeLog(content: string): string {
  let out = content ?? "";
  for (let guard = 0; guard < 10; guard++) {
    const at = locate(out);
    if (!at) break;
    const before = out.slice(0, at.start).trimEnd();
    const after = out.slice(at.end).trimStart();
    out = after ? `${before}\n\n${after}` : before;
  }
  return out;
}

/**
 * Append the dated regeneration entry to a change-log section.
 *
 * Only when the section already has an obvious entry shape (markdown list
 * items, which is what the pipeline templates and the lab imports both use) —
 * an unrecognised format is carried forward untouched rather than having a
 * foreign convention imposed on it. Re-running on the same day is a no-op, so
 * a same-day double regeneration cannot stutter the line.
 */
export function appendRegenerationEntry(section: string, today: string = todayISO()): string {
  const lines = section.split("\n");
  const markers = lines.map((l) => ENTRY_RE.exec(l)?.[1]).filter((m): m is string => !!m);
  if (!markers.length) return section;

  const entry = `${markers[markers.length - 1]} ${today} — ${REGEN_NOTE}`;
  if (lines.some((l) => l.trim() === entry)) return section;
  return `${section.trimEnd()}\n${entry}`;
}

/**
 * Carry an existing change log across a regeneration.
 *
 * @param regenerated  freshly generated document content
 * @param previous     the stored document being replaced (same docType + tier)
 * @returns the regenerated content with any model-written change log removed and
 *          the stored one re-attached at the tail, dated with this run
 */
export function carryChangeLog(
  regenerated: string,
  previous: string | null | undefined,
  today: string = todayISO(),
): string {
  const body = stripChangeLog(regenerated);
  const carried = previous ? extractChangeLog(previous) : null;
  if (!carried) return body;
  return `${body.trimEnd()}\n\n${appendRegenerationEntry(carried, today)}`;
}
