import "server-only";

/**
 * Dynamic Agent Studio — "client data access" grant (Feature: per-AI-step
 * capability grants). Serializes a client's own `clientContextDocs` into a
 * file uploaded to storage and attached as a `context_file`, the SAME
 * upload-then-attach seam `client-agent-feedback-context.ts` already uses for
 * a live client agent's feedback.
 *
 * // DECISION: there is no PRE-EXISTING generic "attach a client's context
 * docs" assembly in submit-custom.ts to reuse — every current context builder
 * (buildXAgentContextFiles, buildRedditAgentContextFiles, etc.) is a bespoke
 * assembly of that agent's OWN structured data (seats, intake, voice
 * profiles), not the generic `clientContextDocs` collection. This module is
 * new, built in the same shape as `buildClientAgentFeedbackFiles` (fetch,
 * render markdown, upload, return [] when there's nothing), rather than a
 * variant of an assembly that does not exist.
 *
 * // DECISION: tier is "internal" only, never "internal-only". "internal"
 * (full analyst-grade markdown; admin/employee only) is the SAME tier the
 * Karos MCP server already hands to a service/job actor via `list_client_context`
 * (see src/lib/mcp/tools.ts) — the one existing precedent for "a running job
 * reads this client's documents". "internal-only" (client-guidelines,
 * action-plan) is staff-facing operating guidance about how to handle this
 * client relationship, not company data for an agent to draw on, and an admin
 * authoring a prompt has no way to see what would be injected if it silently
 * included that tier too — so it is deliberately excluded here.
 */

import { randomUUID } from "crypto";

import { listClientContextDocs } from "@/lib/data";
import { uploadBytes } from "@/lib/storage";
import type { AgentServiceContextFile } from "@/lib/agent-service/types";

export const DYNAMIC_AGENT_CLIENT_CONTEXT_FILENAME = "client-context.md";

/** Per-doc content cap — mirrors the MCP tool's own truncation (tools.ts, CONTEXT_DOC_CONTENT_CAP) so a run never receives materially more than a staff chat session would. */
const PER_DOC_CONTENT_CAP = 20_000;

function renderContextMarkdown(docs: Awaited<ReturnType<typeof listClientContextDocs>>): string {
  const withContent = docs.filter((d) => d.content.trim().length > 0);
  if (withContent.length === 0) return "";
  const sections = withContent.map((doc) => {
    const truncated = doc.content.length > PER_DOC_CONTENT_CAP;
    const body = truncated ? doc.content.slice(0, PER_DOC_CONTENT_CAP) : doc.content;
    const sourceLine = doc.sources && doc.sources.length > 0 ? `\nSources: ${doc.sources.join(", ")}` : "";
    return `## ${doc.docType}\n${sourceLine}\n\n${body}${truncated ? "\n\n[truncated]" : ""}`;
  });
  return [
    "# This client's own documents",
    "",
    "Generated by the onboarding/intel pipeline. Use this to ground the agent's output in real, client-specific facts — never invent a number or claim this file does not support.",
    "",
    ...sections,
  ].join("\n\n");
}

/**
 * Builds the one context file a dynamic-agent run attaches when at least one
 * step has `allowClientData === true`. Returns [] when the client has no
 * internal-tier context docs yet, so the caller can append unconditionally —
 * an agent with the grant but nothing to read just gets a quieter run, not an
 * error.
 */
export async function buildDynamicAgentClientContextFiles(clientId: string): Promise<AgentServiceContextFile[]> {
  const docs = await listClientContextDocs(clientId, "internal");
  const markdown = renderContextMarkdown(docs);
  if (!markdown) return [];

  const { url } = await uploadBytes({
    bytes: Buffer.from(markdown, "utf8"),
    path: `clients/${clientId}/dynamic-agent/client-context/${randomUUID()}/${DYNAMIC_AGENT_CLIENT_CONTEXT_FILENAME}`,
    contentType: "text/markdown",
  });
  return [
    {
      name: DYNAMIC_AGENT_CLIENT_CONTEXT_FILENAME,
      url,
      content_type: "text/markdown",
      description:
        "This client's own internal-tier context documents (competitor analysis, brand voice, market position, etc.), generated by the onboarding/intel pipeline. Only delivered to steps this agent's admin explicitly granted client-data access.",
    },
  ];
}
