"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Badge, Button, Textarea } from "@/components/ui";
import { Icon } from "@/components/icon";
import { pickAgentSlotOptionAction } from "@/lib/actions/slot-option-actions";
import { optionsLead, type ClientXOption } from "@/lib/x-options";

/**
 * Today's three options, and the one gesture that turns one of them into a post
 * (§4.5c, WP-9).
 *
 * TODAY ONLY. The server sends option texts for the current day's slot and no
 * other - a future day's texts never enter the payload, because their existence
 * is the fact the churn rule keeps indistinguishable. This component therefore
 * cannot show tomorrow's even by accident: it has nothing to show.
 *
 * Picking is free. Nothing is generated by choosing - the drafts already exist
 * - so no credit path is touched, and the copy never implies one.
 *
 * The client posts by hand. That is the product for X: they pick, optionally
 * edit, post it themselves, then mark it posted. Each of those is a separate,
 * honest step, and the learning log records all three.
 */
export function OptionPicker({
  clientId,
  slotId,
  options,
}: {
  clientId: string;
  slotId: string;
  options: ClientXOption[];
}) {
  const router = useRouter();
  const [editingRef, setEditingRef] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const [busyRef, setBusyRef] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [, startTransition] = useTransition();

  if (options.length === 0) return null;

  function pick(option: ClientXOption, finalText?: string) {
    setError(null);
    setBusyRef(option.ref);
    startTransition(async () => {
      const result = await pickAgentSlotOptionAction({
        clientId,
        slotId,
        optionRef: option.ref,
        ...(finalText ? { finalText } : {}),
      });
      setBusyRef(null);
      if (result.error) {
        setError(result.error);
        return;
      }
      setEditingRef(null);
      // `router.refresh()` IS the notification: the panel above is server-rendered
      // and re-reads the picked slot. There used to be an `onPicked?.()` here as
      // well, declared and never passed by the one mount
      // (client-agents/agent-detail-panel.tsx) — a second channel for the same
      // fact that was dead in every render.
      router.refresh();
    });
  }

  return (
    <div>
      <div className="mb-2.5">
        <h2 className="font-mono text-[10px] uppercase tracking-[0.08em] text-muted">
          Today&rsquo;s post
        </h2>
        {/* The count is a variable and a one-option day is expected, so the
            plural and the "pick one" both live in optionsLead, where they are
            guarded once and testable. */}
        <p className="mt-1 text-xs text-muted-2">{optionsLead(options.length)}</p>
      </div>

      <ul className="space-y-2">
        {options.map((option) => {
          const editing = editingRef === option.ref;
          const busy = busyRef === option.ref;
          return (
            <li
              key={option.ref}
              className="rounded-[var(--radius)] border border-border bg-surface-2/50 p-3"
            >
              <div className="mb-1.5 flex flex-wrap items-center gap-2">
                <Badge tone="neutral">{option.direction}</Badge>
                {/* Humanised server-side (toClientXOption), and null when the
                    batch heading held nothing a client would recognise — in
                    which case the day says nothing about the account rather
                    than printing a seat number. */}
                {option.account ? (
                  <span className="text-[11px] text-muted-2">{option.account}</span>
                ) : null}
                {option.posts.length > 1 && (
                  <span className="text-[11px] text-muted-2">
                    Thread · {option.posts.length} posts
                  </span>
                )}
              </div>

              {editing ? (
                <Textarea
                  value={draft}
                  onChange={(e) => setDraft(e.target.value)}
                  rows={Math.min(10, Math.max(4, option.posts.join("\n\n").split("\n").length + 1))}
                  aria-label={`Edit ${option.direction}`}
                />
              ) : (
                <div className="space-y-1.5">
                  {option.posts.map((post, i) => (
                    <p
                      key={i}
                      className="whitespace-pre-wrap text-xs leading-relaxed text-foreground"
                    >
                      {normalizeDashes(post)}
                    </p>
                  ))}
                </div>
              )}

              <div className="mt-2 flex flex-wrap items-center gap-1.5">
                {editing ? (
                  <>
                    <Button
                      size="sm"
                      variant="accent"
                      loading={busy}
                      disabled={busy || !draft.trim()}
                      onClick={() => pick(option, draft)}
                    >
                      Use my version
                    </Button>
                    <Button size="sm" variant="ghost" onClick={() => setEditingRef(null)}>
                      Cancel
                    </Button>
                  </>
                ) : (
                  <>
                    <Button
                      size="sm"
                      variant="accent"
                      loading={busy}
                      disabled={busy}
                      onClick={() => pick(option)}
                    >
                      <Icon name="Check" className="h-3.5 w-3.5" /> Use this one
                    </Button>
                    <Button
                      size="sm"
                      variant="ghost"
                      disabled={busy}
                      onClick={() => {
                        setEditingRef(option.ref);
                        setDraft(normalizeDashes(option.posts.join("\n\n")));
                      }}
                    >
                      <Icon name="Pencil" className="h-3.5 w-3.5" /> Edit first
                    </Button>
                  </>
                )}
              </div>
            </li>
          );
        })}
      </ul>
      {error && <p className="mt-2 text-xs text-warning">{error}</p>}
      <p className="mt-2 text-[11px] text-muted-2">
        The one you choose lands in your Workspace ready to post. Mark it posted once it&rsquo;s up
. That&rsquo;s what teaches this agent what you actually publish.
      </p>
    </div>
  );
}

/**
 * What the day shows once a choice has been made. The other two options are
 * gone deliberately: re-offering a direction the client already declined
 * invites second-guessing a decision the system has already acted on.
 *
 * The direction is a BADGE, the same register it has on the cards above — it is
 * a sentence-cased label, so inline it produced a stray capital mid-sentence
 * ("You chose the Contrarian take post for today", #155). Null when the stored
 * ref names no lane, and then the receipt simply does not mention one.
 */
export function OptionPicked({ direction }: { direction: string | null }) {
  return (
    <div className="rounded-[var(--radius)] border border-border bg-surface-2/50 p-3">
      <div className="flex flex-wrap items-center gap-2">
        <Icon name="Check" className="h-4 w-4 text-success" />
        <p className="text-sm text-foreground">You chose today&rsquo;s post</p>
        {direction ? <Badge tone="neutral">{direction}</Badge> : null}
      </div>
      <p className="mt-1 text-[11px] text-muted-2">
        It&rsquo;s in your Workspace ready to post. Mark it posted once it&rsquo;s up.
      </p>
    </div>
  );
}
