import { describe, it, expect } from "vitest";
import {
  extractChangeLog,
  stripChangeLog,
  appendRegenerationEntry,
  carryChangeLog,
} from "../intel/changelog";

/** A stored, lab-imported action plan: frontmatter + body + the provenance trail. */
const STORED = `---
module: action-plan
client: QwQFkfsCXQdwJIKjfeg9
version: 1
status: original
last_updated: 2026-07-24
---

## Objectives

Grow qualified inbound from the developer audience.

## 90-Day Plan

| Phase | Owner | Outcome |
|---|---|---|
| Discovery | Karos | Positioning locked |

## Change Log
- 2026-06-02 — onboarding — initial version.
- 2026-07-24 — refresh import — action plan rebuilt from the lab export.`;

const STORED_LOG = `## Change Log
- 2026-06-02 — onboarding — initial version.
- 2026-07-24 — refresh import — action plan rebuilt from the lab export.`;

/** What the generator returns: same shape, obeying "no Change Log". */
const REGENERATED = `---
module: action-plan
client: QwQFkfsCXQdwJIKjfeg9
version: 1
status: original
last_updated: 2026-07-29
---

## Objectives

Grow qualified inbound from the developer and platform-engineering audience.

## 90-Day Plan

| Phase | Owner | Outcome |
|---|---|---|
| Discovery | Karos | Positioning locked |`;

const countSections = (s: string) => (s.match(/^## /gm) ?? []).length;
const countChangeLogs = (s: string) => (s.match(/^## Change Log$/gm) ?? []).length;

describe("extractChangeLog", () => {
  it("returns the section from its heading to EOF", () => {
    expect(extractChangeLog(STORED)).toBe(STORED_LOG);
  });

  it("stops at the next `## ` heading when the log is mid-document", () => {
    const mid = `## A\n\nbody\n\n## Change Log\n- 2026-01-01 — seed — first.\n\n## Sources\n\n- https://example.com`;
    expect(extractChangeLog(mid)).toBe("## Change Log\n- 2026-01-01 — seed — first.");
  });

  it("is null when the document has no change log", () => {
    expect(extractChangeLog(REGENERATED)).toBeNull();
  });

  it("ignores a `### Change Log` subsection — that is body content", () => {
    expect(extractChangeLog("## Process\n\n### Change Log\n\nHow we log changes.")).toBeNull();
  });
});

describe("stripChangeLog", () => {
  it("removes the section and leaves the rest byte-identical", () => {
    const stripped = stripChangeLog(STORED);
    expect(stripped).not.toContain("## Change Log");
    expect(stripped).toContain("## 90-Day Plan");
    expect(stripped).toContain("| Discovery | Karos | Positioning locked |");
    expect(stripped.startsWith("---\nmodule: action-plan")).toBe(true);
  });

  it("keeps a section that follows the change log", () => {
    const mid = `## A\n\nbody\n\n## Change Log\n- 2026-01-01 — seed — first.\n\n## Sources\n\n- https://example.com`;
    const stripped = stripChangeLog(mid);
    expect(countChangeLogs(stripped)).toBe(0);
    expect(stripped).toContain("## Sources");
    expect(stripped).toContain("## A");
  });

  it("removes every copy when the generator echoed the section twice", () => {
    const doubled = `## Body\n\ntext\n\n## Change Log\n- a\n\n## Change Log\n- b`;
    expect(countChangeLogs(stripChangeLog(doubled))).toBe(0);
  });

  it("is a no-op on a document that has none", () => {
    expect(stripChangeLog(REGENERATED)).toBe(REGENERATED);
  });
});

describe("appendRegenerationEntry", () => {
  it("appends a dated line matching the existing list marker", () => {
    const out = appendRegenerationEntry(STORED_LOG, "2026-07-29");
    expect(out).toBe(
      `${STORED_LOG}\n- 2026-07-29 — Document regenerated by the intel pipeline; earlier entries preserved.`,
    );
  });

  it("does not add a second identical line on the same day", () => {
    const once = appendRegenerationEntry(STORED_LOG, "2026-07-29");
    expect(appendRegenerationEntry(once, "2026-07-29")).toBe(once);
  });

  it("carries an unrecognised entry format unmodified", () => {
    const prose = "## Change Log\n\nRebuilt from the 2026 lab export by the ops team.";
    expect(appendRegenerationEntry(prose, "2026-07-29")).toBe(prose);
  });
});

describe("carryChangeLog", () => {
  it("carries the stored section onto a regenerated document exactly once", () => {
    const out = carryChangeLog(REGENERATED, STORED, "2026-07-29");
    expect(countChangeLogs(out)).toBe(1);
    expect(out).toContain("- 2026-06-02 — onboarding — initial version.");
    expect(out).toContain("- 2026-07-24 — refresh import — action plan rebuilt from the lab export.");
    expect(out).toContain(
      "- 2026-07-29 — Document regenerated by the intel pipeline; earlier entries preserved.",
    );
    // The regenerated body is untouched and still leads the document.
    expect(out.startsWith("---\nmodule: action-plan")).toBe(true);
    expect(out).toContain("developer and platform-engineering audience");
    // …and the log is the tail section.
    expect(out.indexOf("## Change Log")).toBeGreaterThan(out.indexOf("## 90-Day Plan"));
  });

  it("still strips a change log the generator invented", () => {
    const fabricated = `${REGENERATED}\n\n## Change Log\n- 2026-07-29 — pipeline — refreshed all sections.`;
    const out = carryChangeLog(fabricated, null, "2026-07-29");
    expect(countChangeLogs(out)).toBe(0);
    expect(out).not.toContain("refreshed all sections");
    expect(out).toContain("## 90-Day Plan");
  });

  it("lets the stored log win over a fabricated one, with no duplicate section", () => {
    const fabricated = `${REGENERATED}\n\n## Change Log\n- 2026-07-29 — pipeline — invented history.`;
    const out = carryChangeLog(fabricated, STORED, "2026-07-29");
    expect(countChangeLogs(out)).toBe(1);
    expect(out).not.toContain("invented history");
    expect(out).toContain("- 2026-06-02 — onboarding — initial version.");
  });

  it("stays a single section across repeated regenerations, growing by one line each", () => {
    const first = carryChangeLog(REGENERATED, STORED, "2026-07-29");
    const second = carryChangeLog(REGENERATED, first, "2026-08-01");
    const third = carryChangeLog(REGENERATED, second, "2026-09-15");

    expect(countChangeLogs(third)).toBe(1);
    const entries = (extractChangeLog(third) ?? "").split("\n").filter((l) => l.startsWith("- "));
    expect(entries).toHaveLength(5);
    expect(entries[0]).toBe("- 2026-06-02 — onboarding — initial version.");
    expect(entries[2]).toContain("2026-07-29");
    expect(entries[3]).toContain("2026-08-01");
    expect(entries[4]).toContain("2026-09-15");
    // Section count is stable — a regeneration adds a line, never a heading.
    expect(countSections(second)).toBe(countSections(third));
  });

  it("is idempotent when the same run date repeats", () => {
    const first = carryChangeLog(REGENERATED, STORED, "2026-07-29");
    expect(carryChangeLog(REGENERATED, first, "2026-07-29")).toBe(first);
  });

  it("carries a client-tier log as-is rather than inventing tier policy", () => {
    const clientDoc = `## Summary\n\nCondensed.\n\n## Change Log\n- 2026-07-24 — import — client copy.`;
    const out = carryChangeLog("## Summary\n\nCondensed again.", clientDoc, "2026-07-29");
    expect(out).toContain("- 2026-07-24 — import — client copy.");
    expect(countChangeLogs(out)).toBe(1);
  });

  it("returns the stripped body when there is no prior document", () => {
    expect(carryChangeLog(REGENERATED, undefined, "2026-07-29")).toBe(REGENERATED);
  });
});

describe("corrections path (applyDocCorrections) needs no carry", () => {
  // applyDocCorrections rewrites an EXISTING document in place and discards any
  // output whose `## ` heading count differs from the input's. A `## Change Log`
  // is counted by that guard, so a correction pass that dropped the section is
  // rejected wholesale and the caller receives the original — with its log.
  it("counts `## Change Log` in the structural guard that protects it", () => {
    const withLog = countSections(STORED);
    const withoutLog = countSections(stripChangeLog(STORED));
    expect(withLog).toBe(withoutLog + 1);
  });
});
